### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by liza-alpinia** [marcelTBI/GenomeScreen#2]
Good day!

I studied your article and again there was a question about data preprocessing - I did not understand the described normalization stage - 'the bin counts corresponding to autosomal chromosomes for each sample were normalized to the identical number of reads (i.e., each bin was divided so the sum of all bins on autosomal chromosomes would be the same for each sample)'
If we split the reference into bins, then there will be the same number of bins for each of the samples. Then the question arises, what does the described stage do.

**Comment by marcelTBI** [comment]
Hi,

yeah, the wording is a bit "rough", maybe the better would be something along the lines: 'the bin counts corresponding to autosomal chromosomes for each sample were normalized to the identical number of reads (i.e., each **bin count** was divided so the sum of all **bin counts** on autosomal chromosomes would be the same for each sample)' - for example, if a sample had 2,000,000 reads and some bin had 7 reads in it, after normalizing this sample to 1,000,000 reads, this bin would have 3.5 reads (note that we can go from integers to floats here, but that is the case also for other types of normalization).

Is this clear now?

**Comment by liza-alpinia** [comment]
Hi!
Thank you for your quick reply.
Now it became clear.
