### ISSUE TITLE
rpy2 problem 

### ISSUE THREAD

**Issue by xiucz** [marcelTBI/GenomeScreen#3]
Hi,
I think rpy2 is not easy to install, even if I use the right version. When I check the source code, the main part of rpy2 is the `call_cbs_r` function:
https://github.com/marcelTBI/GenomeScreen/blob/ad253308139a972698e25311f5b70daab8179b0b/genome_screen.py#L562

If we slightly modify the `call_cbs_r` code and use `os.system` to run the R code, it will be easier.
```
def call_cbs_r(bins_norm, rscript, window):
    # compute positions
    positions = gen_pos(bins_norm['chromosome'], window)
    # load the library
    #rpy2.robjects.r.source(rscript)

    # convert data to R format
    #cbs_data = rpy2.robjects.numpy2ri.py2ri(bins_norm['bins_PCA'][ind_valid])
    # cbs_data = rpy2.robjects.conversion.py2rpy(bins_norm['bins_PCA'][ind_valid])
    #cbs_chromosome = rpy2.robjects.numpy2ri.py2ri(bins_norm['chromosome'][ind_valid])
    #cbs_positions = rpy2.robjects.numpy2ri.py2ri(positions[ind_valid])

    # call the CBS function (this line takes ~11secs out of 12.5secs)
    #ret = rpy2.robjects.r.CBS(cbs_data, cbs_chromosome, cbs_positions)
    os.system("Rscript cbs_lib.R")
    ret = pd.read_csv("cbs.out", sep = "\t")
    cbs_r = ret
    # covert the result to dataframe and fix it
    #cbs_r = rpy2.robjects.pandas2ri.ri2py(ret)
    cbs_r = cbs_r.drop(['ID'], axis=1)

```
And add some line here
https://github.com/marcelTBI/GenomeScreen/blob/ad253308139a972698e25311f5b70daab8179b0b/genome_screen.py#L636

```
    gaps_dict, bins_norm = normalize(args, bins_data, mean_data, ind_filtered)
    ind_valid = ~np.isnan(bins_norm['bins_PCA'])
    window = args.window
    positions = gen_pos(bins_norm['chromosome'], window)
    a = bins_norm['bins_PCA'][ind_valid]
    np.savetxt('bin.out', a, delimiter='\n')
    b = bins_norm['chromosome'][ind_valid]
    np.savetxt('chromosome.out', b, delimiter='\n')
    c = positions[ind_valid]
    np.savetxt('position.out', b, delimiter='\n')
# call the CBS in R
```
And also  modify `cbs_lib.R` a little to read the  `bins, chromosomes, positions ` option
```
df1 <- read.table("bin.out")
bins <- as.vector(df1$V1)

df2 <- read.table("chromosome.out")
chromosomes <- as.vector(df2$V1)

df3 <- read.table("position.out")
positions <- as.vector(df3$V1)
```

However, the result is a little strange: 
![image](https://user-images.githubusercontent.com/12706146/213053574-cac17dac-eb3c-414e-9475-91d37aa269dd.png)

here is my command 
```
python genome_screen.py -m data/means_c15_genomic.npy -b genomescreen_data/12462.npz \
-o . -k --filter-file data/cnv_gaps_GScurated.txt --x-count 1
```

**Comment by marcelTBI** [comment]
hmmm, actually I remember this was my first approach to calling R scripts, but then I needed to speed up the computation for the publication, where we were running around a million CNV callings. So the approach is definitely feasible (it was done at some point as you suggest), although a bit too slow. However, I do not know why you get zeros in most of the columns (since the "level" column seems alright, I would suspect some weird rounding or some conversion error) - did you check directly the R outputs if they are correct? And inputs? I am not so proficient in R to suggest anything more, sorry.

**Comment by xiucz** [comment]
ok, thank you, ^…^
