### ISSUE TITLE
how to do loess normalization

### ISSUE THREAD

**Issue by lookgene** [marcelTBI/GenomeScreen#4]
Can you provide the script to do loess normalization

**Comment by marcelTBI** [comment]
Hi! Unfortunately, the loess normalization scripts are highly embedded into our pipeline, and extracting them is no easy task. However, loess normalization is a reasonably straightforward procedure multiple times described in relevant literature. For example: Benjamini, Y., & Speed, T. P. (2012). Summarizing and correcting the GC content bias in high-throughput sequencing.
